In [1]:
import pandas as pd
odds_df = pd.read_csv('../dataset/premier/lightgbm/lightgbm_base_odds_premier.csv')
odds_df = odds_df.sort_values(by=['match_year','match_month','match_day','match_hour','match_round','home_team','away_team']).reset_index(drop=True)
odds_df.head()

,10bet_1,10bet_2,10bet_X,10bet_opening_1,10bet_opening_2,10bet_opening_X,188bet_1,188bet_2,188bet_X,188bet_opening_1,...,youwin_1,youwin_2,youwin_X,youwin_opening_1,youwin_opening_2,youwin_opening_X,label,match_day,match_month,match_year
0,1.12,20.70,7.96,1.15,21.60,7.63,1.18,26.00,7.50,1.22,...,1.13,17.00,6.00,1.20,13.00,5.5,1,15,8,2009
1,1.73,5.14,3.49,1.66,5.09,3.45,1.77,5.30,3.60,1.81,...,1.65,4.80,3.50,NaN,NaN,NaN,2,15,8,2009
2,3.15,2.31,3.27,3.25,2.25,3.22,3.10,2.36,3.40,3.15,...,3.00,2.20,3.25,3.25,2.10,NaN,2,15,8,2009
3,2.23,3.29,3.26,2.27,3.34,3.22,2.27,3.40,3.35,2.33,...,2.20,3.20,3.25,2.10,3.25,NaN,2,15,8,2009
4,2.87,2.61,3.12,2.96,2.57,3.08,2.90,2.60,3.30,2.95,...,2.75,2.63,3.10,2.25,3.00,3.2,2,15,8,2009

In [4]:
bet365 = odds_df[['bet365_1','bet365_X','bet365_2','label','match_day','match_month','match_year','match_hour','match_round']]
bet365.head()

,bet365_1,bet365_X,bet365_2,label,match_day,match_month,match_year,match_hour,match_round
0,1.20,7.00,21.00,1,15,8,2009,13,1
1,1.73,3.60,5.00,2,15,8,2009,16,1
2,3.40,3.20,2.25,2,15,8,2009,16,1
3,2.29,3.25,3.25,2,15,8,2009,16,1
4,2.88,3.25,2.50,2,15,8,2009,16,1

In [45]:
# baseline che usa solo le quote
subset_bet365 = bet365[(bet365.match_round<34) & (bet365.match_year>2016)].reset_index(drop=True)
result = []
for p1,pX,p2 in zip(subset_bet365['bet365_1'], subset_bet365['bet365_X'], subset_bet365['bet365_2']):
    if min([p1,pX,p2]) == p1: result.append(1)
    elif min([p1,pX,p2]) == pX: result.append(0)
    else: result.append(2)

correct = 0
for ind,true,predicted in zip(subset_bet365.index, subset_bet365.label, result):
    if true == predicted:
        correct+=1
correct*100 / subset_bet365.shape[0]

58.4788029925187

In [46]:
# baseline che usa solo le quote
result = []
for p1,pX,p2 in zip(bet365['bet365_1'], bet365['bet365_X'], bet365['bet365_2']):
    if min([p1,pX,p2]) == p1: result.append(1)
    elif min([p1,pX,p2]) == pX: result.append(0)
    else: result.append(2)

correct = 0
for ind,true,predicted in zip(bet365.index, bet365.label, result):
    if true == predicted:
        correct+=1
correct*100 / bet365.shape[0]

54.71052631578947

In [62]:
bet365.label.tolist().count(2) / bet365.shape[0]

0.29

In [65]:
# predizioni col modello da 60% accuracy
best_preds = [1,1,2,1,1,2,2,2,1,1,1,1,1,2,2,1,1,1,2,1,1,2,0,1,1,1,1,2,1,1,1,2,1,2,1,1,1,1,0,1,2,2,1,1,1,1,1,1,1,2]

In [66]:
bet365.tail(50)

,bet365_1,bet365_X,bet365_2,label,match_day,match_month,match_year,match_hour,match_round
3750,2.70,3.20,2.87,1,13,4,2019,16,34
3751,1.33,5.75,9.50,1,13,4,2019,18,34
3752,13.00,6.75,1.25,2,14,4,2019,15,34
3753,1.72,3.90,5.25,1,14,4,2019,17,34
3754,3.70,3.70,2.05,2,15,4,2019,21,34
3755,2.00,3.30,4.50,2,16,4,2019,20,31
3756,1.28,6.50,10.50,1,20,4,2019,13,35
3757,1.70,4.33,4.75,2,20,4,2019,16,35
3758,4.20,3.60,1.95,2,20,4,2019,16,35
3759,3.20,3.60,2.30,0,20,4,2019,16,35
3760,1.95,3.20,5.00,0,20,4,2019,16,35
3761,2.45,3.10,3.40,1,20,4,2019,18,35
3762,3.25,3.60,2.25,1,21,4,2019,14,35
3763,1.53,4.75,6.00,2,21,4,2019,17,35
3764,17.00,8.00,1.18,2,21,4,2019,17,35
3765,1.22,7.00,15.00,0,22,4,2019,21,35
3766,2.20,3.50,3.50,0,23,4,2019,20,31
3767,1.25,6.50,13.00,1,23,4,2019,20,33
3768,2.75,3.40,2.70,1,24,4,2019,20,31
3769,6.50,4.80,1.50,2,24,4,2019,21,31
3770,1.06,19.00,34.00,1,26,4,2019,21,36
3771,1.36,5.50,9.00,2,27,4,2019,13,36
3772,2.90,3.60,2.45,0,27,4,2019,16,36
3773,2.25,3.70,3.20,1,27,4,2019,16,36
3774,1.80,4.00,4.50,0,27,4,2019,16,36
3775,2.62,3.30,2.90,2,27,4,2019,16,36
3776,2.20,3.40,3.60,0,27,4,2019,18,36
3777,2.62,3.75,2.62,1,28,4,2019,13,36
3778,19.00,10.00,1.14,2,28,4,2019,15,36
3779,2.75,3.40,2.70,0,28,4,2019,17,36
3780,1.65,4.00,5.75,1,3,5,2019,21,37
3781,5.75,4.75,1.55,1,4,5,2019,13,37
3782,2.37,3.70,3.00,1,4,5,2019,16,37
3783,1.50,4.50,7.50,1,4,5,2019,16,37
3784,2.50,3.90,2.70,2,4,5,2019,18,37
3785,9.50,5.75,1.33,2,4,5,2019,20,37
3786,1.30,6.00,11.00,1,5,5,2019,15,37
3787,9.00,6.00,1.33,0,5,5,2019,15,37
3788,1.28,6.00,12.00,0,5,5,2019,17,37
3789,1.18,9.00,15.00,1,6,5,2019,21,37
3790,15.00,8.00,1.20,2,12,5,2019,16,38
3791,2.50,3.70,2.80,2,12,5,2019,16,38
3792,1.80,4.40,4.10,1,12,5,2019,16,38
3793,2.45,3.60,2.90,2,12,5,2019,16,38
3794,2.37,3.80,2.90,0,12,5,2019,16,38
3795,1.30,6.00,11.00,1,12,5,2019,16,38
3796,1.30,6.25,10.00,2,12,5,2019,16,38
3797,1.40,5.00,8.50,0,12,5,2019,16,38
3798,1.90,3.80,4.20,0,12,5,2019,16,38
3799,2.10,3.90,3.40,2,12,5,2019,16,38

In [67]:
correct = 0
for true,predicted in zip(bet365.tail(50).label, best_preds):
    if true == predicted:
        correct+=1
correct

25