In [25]:
import pandas as pd
df = pd.read_csv('../dataset/serie_a/lightgbm/lightgbm_base_odds_serie_a.csv')
df = df.sort_values(by=['match_year','match_month','match_day','match_hour','match_round','home_team','away_team']).reset_index(drop=True)
df.head()

,10bet_1,10bet_2,10bet_X,10bet_opening_1,10bet_opening_2,10bet_opening_X,188bet_1,188bet_2,188bet_X,188bet_opening_1,...,youwin_1,youwin_2,youwin_X,youwin_opening_1,youwin_opening_2,youwin_opening_X,label,match_day,match_month,match_year
0,3.63,2.08,3.12,3.52,2.14,3.08,4.00,2.09,3.30,3.90,...,3.40,2.10,3.2,2.95,2.29,3.10,0,22,8,2009
1,4.19,1.89,3.20,4.28,1.83,3.25,4.34,1.97,3.35,4.30,...,4.00,1.91,3.2,3.70,1.95,NaN,2,22,8,2009
2,1.20,12.71,5.82,1.24,12.54,5.87,1.25,15.50,6.25,1.21,...,1.20,12.00,5.5,NaN,11.00,5.75,0,23,8,2009
3,2.69,2.70,3.16,2.65,2.74,3.12,2.80,2.75,3.20,2.74,...,2.50,2.75,3.1,2.40,NaN,NaN,2,23,8,2009
4,2.16,3.35,3.29,2.24,3.22,3.20,2.13,3.55,3.50,2.17,...,2.25,3.10,3.2,2.40,2.70,3.10,1,23,8,2009

In [26]:
sorted(df.columns)

['10bet_1',
 '10bet_2',
 '10bet_X',
 '10bet_opening_1',
 '10bet_opening_2',
 '10bet_opening_X',
 '188bet_1',
 '188bet_2',
 '188bet_X',
 '188bet_opening_1',
 '188bet_opening_2',
 '188bet_opening_X',
 '1xbet_1',
 '1xbet_2',
 '1xbet_X',
 '1xbet_opening_1',
 '1xbet_opening_2',
 '1xbet_opening_X',
 '888sport_1',
 '888sport_2',
 '888sport_X',
 '888sport_opening_1',
 '888sport_opening_2',
 '888sport_opening_X',
 'away_goals',
 'away_team',
 'bet-at-home_1',
 'bet-at-home_2',
 'bet-at-home_X',
 'bet-at-home_opening_1',
 'bet-at-home_opening_2',
 'bet-at-home_opening_X',
 'bet365_1',
 'bet365_2',
 'bet365_X',
 'bet365_opening_1',
 'bet365_opening_2',
 'bet365_opening_X',
 'betclic_1',
 'betclic_2',
 'betclic_X',
 'betclic_opening_1',
 'betclic_opening_2',
 'betclic_opening_X',
 'betfair exchange_1',
 'betfair exchange_2',
 'betfair exchange_X',
 'betfair exchange_opening_1',
 'betfair exchange_opening_2',
 'betfair exchange_opening_X',
 'betfair_1',
 'betfair_2',
 'betfair_X',
 'betfair_opening_1',
 'betfair_opening_2',
 'betfair_opening_X',
 'betsafe_1',
 'betsafe_2',
 'betsafe_X',
 'betsafe_opening_1',
 'betsafe_opening_2',
 'betsafe_opening_X',
 'betsson_1',
 'betsson_2',
 'betsson_X',
 'betsson_opening_1',
 'betsson_opening_2',
 'betsson_opening_X',
 'betvictor_1',
 'betvictor_2',
 'betvictor_X',
 'betvictor_opening_1',
 'betvictor_opening_2',
 'betvictor_opening_X',
 'betway_1',
 'betway_2',
 'betway_X',
 'betway_opening_1',
 'betway_opening_2',
 'betway_opening_X',
 'bwin_1',
 'bwin_2',
 'bwin_X',
 'bwin_opening_1',
 'bwin_opening_2',
 'bwin_opening_X',
 'comeon_1',
 'comeon_2',
 'comeon_X',
 'comeon_opening_1',
 'comeon_opening_2',
 'comeon_opening_X',
 'home_goals',
 'home_team',
 'interwetten_1',
 'interwetten_2',
 'interwetten_X',
 'interwetten_opening_1',
 'interwetten_opening_2',
 'interwetten_opening_X',
 'label',
 'league_year',
 'match_date',
 'match_day',
 'match_hour',
 'match_month',
 'match_round',
 'match_year',
 'paddy power_1',
 'paddy power_2',
 'paddy power_X',
 'paddy power_opening_1',
 'paddy power_opening_2',
 'paddy power_opening_X',
 'pinnacle_1',
 'pinnacle_2',
 'pinnacle_X',
 'pinnacle_opening_1',
 'pinnacle_opening_2',
 'pinnacle_opening_X',
 'sbobet_1',
 'sbobet_2',
 'sbobet_X',
 'sbobet_opening_1',
 'sbobet_opening_2',
 'sbobet_opening_X',
 'unibet_1',
 'unibet_2',
 'unibet_X',
 'unibet_opening_1',
 'unibet_opening_2',
 'unibet_opening_X',
 'william hill_1',
 'william hill_2',
 'william hill_X',
 'william hill_opening_1',
 'william hill_opening_2',
 'william hill_opening_X',
 'youwin_1',
 'youwin_2',
 'youwin_X',
 'youwin_opening_1',
 'youwin_opening_2',
 'youwin_opening_X']

In [28]:
user_pref_df = pd.read_csv('../dataset/serie_a/transformed/user_prefs_serie_a.csv')
user_pref_df = user_pref_df.rename(columns={'match_year':'league_year'})
user_pref_df.head()

,league_year,match_round,home_team,away_team,ht_win_pred_transfer,draw_pred_transfer,at_win_pred_transfer
0,2009,1,Bologna,Fiorentina,4.8,19.0,76.2
1,2009,1,Siena,AC Milan,0.0,9.5,90.5
2,2009,1,Inter,Bari,100.0,0.0,0.0
3,2009,1,US Palermo,SSC Napoli,30.0,35.0,35.0
4,2009,1,AS Livorno,Cagliari Calcio,40.0,30.0,30.0

In [29]:
sorted(set(df.away_team))

['AC Milan',
 'AS Roma',
 'Atalanta',
 'Bari',
 'Benevento',
 'Bologna',
 'Brescia',
 'Cagliari',
 'Carpi',
 'Catania',
 'Cesena',
 'Chievo',
 'Crotone',
 'Empoli',
 'Fiorentina',
 'Frosinone',
 'Genoa',
 'Inter',
 'Juventus',
 'Lazio',
 'Lecce',
 'Livorno',
 'Napoli',
 'Novara',
 'Palermo',
 'Parma',
 'Pescara',
 'Sampdoria',
 'Sassuolo',
 'Siena',
 'Spal',
 'Torino',
 'Udinese',
 'Verona']

In [30]:
sorted(set(user_pref_df.away_team))

['AC Milan',
 'AS Livorno',
 'AS Roma',
 'Atalanta',
 'Bari',
 'Benevento',
 'Bologna',
 'Brescia',
 'Cagliari Calcio',
 'Carpi',
 'Catania',
 'Cesena',
 'Chievo Verona',
 'Crotone',
 'FC Empoli',
 'Fiorentina',
 'Frosinone',
 'Genoa',
 'Hellas Verona',
 'Inter',
 'Juventus',
 'Lazio',
 'Lecce',
 'Novara',
 'Parma',
 'Pescara',
 'SPAL',
 'SSC Napoli',
 'Sampdoria',
 'Sassuolo',
 'Siena',
 'Torino',
 'US Palermo',
 'Udinese',
 'Udinese Calcio']

In [31]:
user_pref_df.loc[user_pref_df.home_team == 'Cagliari Calcio', 'home_team'] = 'Cagliari'
user_pref_df.loc[user_pref_df.away_team == 'Cagliari Calcio', 'away_team'] = 'Cagliari'
user_pref_df.loc[user_pref_df.home_team == 'Chievo Verona', 'home_team'] = 'Chievo'
user_pref_df.loc[user_pref_df.away_team == 'Chievo Verona', 'away_team'] = 'Chievo'
user_pref_df.loc[user_pref_df.home_team == 'FC Empoli', 'home_team'] = 'Empoli'
user_pref_df.loc[user_pref_df.away_team == 'FC Empoli', 'away_team'] = 'Empoli'
user_pref_df.loc[user_pref_df.home_team == 'AS Livorno', 'home_team'] = 'Livorno'
user_pref_df.loc[user_pref_df.away_team == 'AS Livorno', 'away_team'] = 'Livorno'
user_pref_df.loc[user_pref_df.home_team == 'SSC Napoli', 'home_team'] = 'Napoli'
user_pref_df.loc[user_pref_df.away_team == 'SSC Napoli', 'away_team'] = 'Napoli'
user_pref_df.loc[user_pref_df.home_team == 'Udinese Calcio', 'home_team'] = 'Udinese'
user_pref_df.loc[user_pref_df.away_team == 'Udinese Calcio', 'away_team'] = 'Udinese'
user_pref_df.loc[user_pref_df.home_team == 'US Palermo', 'home_team'] = 'Palermo'
user_pref_df.loc[user_pref_df.away_team == 'US Palermo', 'away_team'] = 'Palermo'
user_pref_df.loc[user_pref_df.home_team == 'SPAL', 'home_team'] = 'Spal'
user_pref_df.loc[user_pref_df.away_team == 'SPAL', 'away_team'] = 'Spal'
user_pref_df.loc[user_pref_df.home_team == 'Hellas Verona', 'home_team'] = 'Verona'
user_pref_df.loc[user_pref_df.away_team == 'Hellas Verona', 'away_team'] = 'Verona'

In [32]:
sorted(set(user_pref_df.away_team)) == sorted(set(df.away_team)) and sorted(set(user_pref_df.home_team)) == sorted(set(df.home_team))

True

In [34]:
user_pref_df.sort_values(by=['league_year','match_round','home_team','away_team']).head(19)

,league_year,match_round,home_team,away_team,ht_win_pred_transfer,draw_pred_transfer,at_win_pred_transfer
0,2009,1,Bologna,Fiorentina,4.8,19.0,76.2
6,2009,1,Catania,Sampdoria,30.0,35.0,35.0
5,2009,1,Genoa,AS Roma,28.6,23.8,47.6
2,2009,1,Inter,Bari,100.0,0.0,0.0
9,2009,1,Juventus,Chievo,85.7,14.3,0.0
8,2009,1,Lazio,Atalanta,95.2,4.8,0.0
4,2009,1,Livorno,Cagliari,40.0,30.0,30.0
3,2009,1,Palermo,Napoli,30.0,35.0,35.0
1,2009,1,Siena,AC Milan,0.0,9.5,90.5
7,2009,1,Udinese,Parma,81.0,9.5,9.5
11,2009,2,AC Milan,Inter,20.0,55.0,25.0
12,2009,2,AS Roma,Juventus,9.5,28.6,61.9
13,2009,2,Atalanta,Genoa,19.0,28.6,52.4
10,2009,2,Bari,Bologna,36.8,36.8,26.3
17,2009,2,Cagliari,Siena,42.9,38.1,19.0
19,2009,2,Chievo,Lazio,4.5,13.6,81.8
16,2009,2,Fiorentina,Palermo,72.7,22.7,4.5
15,2009,2,Napoli,Livorno,90.5,9.5,0.0
18,2009,2,Parma,Catania,81.0,14.3,4.8

In [35]:
class_df = pd.read_csv('../dataset/serie_a/transformed/classifica_serie_a_0919.csv')
class_df = class_df.rename(columns={'match_year':'league_year'})
class_df.head()

,league_year,match_round,team,team_rank,team_points,team_goal_difference,team_goal_fatti,team_goal_subiti
0,2009,2,Genoa,1,3,1,3,2
1,2009,2,AC Milan,2,3,1,2,1
2,2009,2,Sampdoria,3,3,1,2,1
3,2009,2,US Palermo,4,3,1,2,1
4,2009,2,Juventus,5,3,1,1,0

In [36]:
[x for x in list(set(class_df.team)) if x not in list(set(user_pref_df.away_team))]

['Chievo Verona',
 'FC Empoli',
 'SPAL',
 'AS Livorno',
 'Hellas Verona',
 'US Palermo',
 'Cagliari Calcio',
 'Udinese Calcio',
 'SSC Napoli']

In [37]:
class_df.at[class_df.team=='Chievo Verona', 'team'] = 'Chievo'
class_df.at[class_df.team=='Udinese Calcio', 'team'] = 'Udinese'
class_df.at[class_df.team=='SSC Napoli', 'team'] = 'Napoli'
class_df.at[class_df.team=='SPAL', 'team'] = 'Spal'
class_df.at[class_df.team=='FC Empoli', 'team'] = 'Empoli'
class_df.at[class_df.team=='Hellas Verona', 'team'] = 'Verona'
class_df.at[class_df.team=='AS Livorno', 'team'] = 'Livorno'
class_df.at[class_df.team=='US Palermo', 'team'] = 'Palermo'
class_df.at[class_df.team=='Cagliari Calcio', 'team'] = 'Cagliari'

In [38]:
sorted(list(set(class_df.team))) == sorted(set(user_pref_df.away_team)) == sorted(set(df.away_team))

True

In [77]:
tmp = pd.merge(user_pref_df, class_df.add_prefix('home_'), how='left', left_on=['league_year','match_round','home_team'], right_on=['home_league_year','home_match_round','home_team']).fillna(0).drop(['home_league_year','home_match_round'],axis=1)
tmp = pd.merge(tmp, class_df.add_prefix('away_'), how='left', left_on=['league_year','match_round','away_team'], right_on=['away_league_year','away_match_round','away_team']).fillna(0).drop(['away_league_year','away_match_round'],axis=1)
tmp[tmp.columns[7:]] = tmp[tmp.columns[7:]].astype(int)
tmp.head()

,league_year,match_round,home_team,away_team,ht_win_pred_transfer,draw_pred_transfer,at_win_pred_transfer,home_team_rank,home_team_points,home_team_goal_difference,home_team_goal_fatti,home_team_goal_subiti,away_team_rank,away_team_points,away_team_goal_difference,away_team_goal_fatti,away_team_goal_subiti
0,2009,1,Bologna,Fiorentina,4.8,19.0,76.2,0,0,0,0,0,0,0,0,0,0
1,2009,1,Siena,AC Milan,0.0,9.5,90.5,0,0,0,0,0,0,0,0,0,0
2,2009,1,Inter,Bari,100.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
3,2009,1,Palermo,Napoli,30.0,35.0,35.0,0,0,0,0,0,0,0,0,0,0
4,2009,1,Livorno,Cagliari,40.0,30.0,30.0,0,0,0,0,0,0,0,0,0,0

In [82]:
tmp_df = pd.merge(df, tmp, how='left',on=['league_year', 'match_round','home_team','away_team'])
tmp_df.head()

,10bet_1,10bet_2,10bet_X,10bet_opening_1,10bet_opening_2,10bet_opening_X,188bet_1,188bet_2,188bet_X,188bet_opening_1,...,home_team_rank,home_team_points,home_team_goal_difference,home_team_goal_fatti,home_team_goal_subiti,away_team_rank,away_team_points,away_team_goal_difference,away_team_goal_fatti,away_team_goal_subiti
0,3.63,2.08,3.12,3.52,2.14,3.08,4.00,2.09,3.30,3.90,...,0,0,0,0,0,0,0,0,0,0
1,4.19,1.89,3.20,4.28,1.83,3.25,4.34,1.97,3.35,4.30,...,0,0,0,0,0,0,0,0,0,0
2,1.20,12.71,5.82,1.24,12.54,5.87,1.25,15.50,6.25,1.21,...,0,0,0,0,0,0,0,0,0,0
3,2.69,2.70,3.16,2.65,2.74,3.12,2.80,2.75,3.20,2.74,...,0,0,0,0,0,0,0,0,0,0
4,2.16,3.35,3.29,2.24,3.22,3.20,2.13,3.55,3.50,2.17,...,0,0,0,0,0,0,0,0,0,0

In [83]:
sorted(tmp_df.columns)

['10bet_1',
 '10bet_2',
 '10bet_X',
 '10bet_opening_1',
 '10bet_opening_2',
 '10bet_opening_X',
 '188bet_1',
 '188bet_2',
 '188bet_X',
 '188bet_opening_1',
 '188bet_opening_2',
 '188bet_opening_X',
 '1xbet_1',
 '1xbet_2',
 '1xbet_X',
 '1xbet_opening_1',
 '1xbet_opening_2',
 '1xbet_opening_X',
 '888sport_1',
 '888sport_2',
 '888sport_X',
 '888sport_opening_1',
 '888sport_opening_2',
 '888sport_opening_X',
 'at_win_pred_transfer',
 'away_goals',
 'away_team',
 'away_team_goal_difference',
 'away_team_goal_fatti',
 'away_team_goal_subiti',
 'away_team_points',
 'away_team_rank',
 'bet-at-home_1',
 'bet-at-home_2',
 'bet-at-home_X',
 'bet-at-home_opening_1',
 'bet-at-home_opening_2',
 'bet-at-home_opening_X',
 'bet365_1',
 'bet365_2',
 'bet365_X',
 'bet365_opening_1',
 'bet365_opening_2',
 'bet365_opening_X',
 'betclic_1',
 'betclic_2',
 'betclic_X',
 'betclic_opening_1',
 'betclic_opening_2',
 'betclic_opening_X',
 'betfair exchange_1',
 'betfair exchange_2',
 'betfair exchange_X',
 'betfair exchange_opening_1',
 'betfair exchange_opening_2',
 'betfair exchange_opening_X',
 'betfair_1',
 'betfair_2',
 'betfair_X',
 'betfair_opening_1',
 'betfair_opening_2',
 'betfair_opening_X',
 'betsafe_1',
 'betsafe_2',
 'betsafe_X',
 'betsafe_opening_1',
 'betsafe_opening_2',
 'betsafe_opening_X',
 'betsson_1',
 'betsson_2',
 'betsson_X',
 'betsson_opening_1',
 'betsson_opening_2',
 'betsson_opening_X',
 'betvictor_1',
 'betvictor_2',
 'betvictor_X',
 'betvictor_opening_1',
 'betvictor_opening_2',
 'betvictor_opening_X',
 'betway_1',
 'betway_2',
 'betway_X',
 'betway_opening_1',
 'betway_opening_2',
 'betway_opening_X',
 'bwin_1',
 'bwin_2',
 'bwin_X',
 'bwin_opening_1',
 'bwin_opening_2',
 'bwin_opening_X',
 'comeon_1',
 'comeon_2',
 'comeon_X',
 'comeon_opening_1',
 'comeon_opening_2',
 'comeon_opening_X',
 'draw_pred_transfer',
 'home_goals',
 'home_team',
 'home_team_goal_difference',
 'home_team_goal_fatti',
 'home_team_goal_subiti',
 'home_team_points',
 'home_team_rank',
 'ht_win_pred_transfer',
 'interwetten_1',
 'interwetten_2',
 'interwetten_X',
 'interwetten_opening_1',
 'interwetten_opening_2',
 'interwetten_opening_X',
 'label',
 'league_year',
 'match_date',
 'match_day',
 'match_hour',
 'match_month',
 'match_round',
 'match_year',
 'paddy power_1',
 'paddy power_2',
 'paddy power_X',
 'paddy power_opening_1',
 'paddy power_opening_2',
 'paddy power_opening_X',
 'pinnacle_1',
 'pinnacle_2',
 'pinnacle_X',
 'pinnacle_opening_1',
 'pinnacle_opening_2',
 'pinnacle_opening_X',
 'sbobet_1',
 'sbobet_2',
 'sbobet_X',
 'sbobet_opening_1',
 'sbobet_opening_2',
 'sbobet_opening_X',
 'unibet_1',
 'unibet_2',
 'unibet_X',
 'unibet_opening_1',
 'unibet_opening_2',
 'unibet_opening_X',
 'william hill_1',
 'william hill_2',
 'william hill_X',
 'william hill_opening_1',
 'william hill_opening_2',
 'william hill_opening_X',
 'youwin_1',
 'youwin_2',
 'youwin_X',
 'youwin_opening_1',
 'youwin_opening_2',
 'youwin_opening_X']

In [84]:
final_df = tmp_df.drop(['match_date','home_team','away_team','home_goals','away_goals'], axis=1)
final_df = final_df.sort_values(by = ['league_year', 'match_round']).reset_index(drop=True)
final_df = final_df.fillna(0)
final_df.head()

,10bet_1,10bet_2,10bet_X,10bet_opening_1,10bet_opening_2,10bet_opening_X,188bet_1,188bet_2,188bet_X,188bet_opening_1,...,home_team_rank,home_team_points,home_team_goal_difference,home_team_goal_fatti,home_team_goal_subiti,away_team_rank,away_team_points,away_team_goal_difference,away_team_goal_fatti,away_team_goal_subiti
0,3.63,2.08,3.12,3.52,2.14,3.08,4.00,2.09,3.30,3.90,...,0,0,0,0,0,0,0,0,0,0
1,4.19,1.89,3.20,4.28,1.83,3.25,4.34,1.97,3.35,4.30,...,0,0,0,0,0,0,0,0,0,0
2,1.20,12.71,5.82,1.24,12.54,5.87,1.25,15.50,6.25,1.21,...,0,0,0,0,0,0,0,0,0,0
3,2.69,2.70,3.16,2.65,2.74,3.12,2.80,2.75,3.20,2.74,...,0,0,0,0,0,0,0,0,0,0
4,2.16,3.35,3.29,2.24,3.22,3.20,2.13,3.55,3.50,2.17,...,0,0,0,0,0,0,0,0,0,0

In [112]:
sorted(final_df.columns)

['10bet_1',
 '10bet_2',
 '10bet_X',
 '10bet_opening_1',
 '10bet_opening_2',
 '10bet_opening_X',
 '188bet_1',
 '188bet_2',
 '188bet_X',
 '188bet_opening_1',
 '188bet_opening_2',
 '188bet_opening_X',
 '1xbet_1',
 '1xbet_2',
 '1xbet_X',
 '1xbet_opening_1',
 '1xbet_opening_2',
 '1xbet_opening_X',
 '888sport_1',
 '888sport_2',
 '888sport_X',
 '888sport_opening_1',
 '888sport_opening_2',
 '888sport_opening_X',
 'at_win_pred_transfer',
 'away_team_goal_difference',
 'away_team_goal_fatti',
 'away_team_goal_subiti',
 'away_team_points',
 'away_team_rank',
 'bet-at-home_1',
 'bet-at-home_2',
 'bet-at-home_X',
 'bet-at-home_opening_1',
 'bet-at-home_opening_2',
 'bet-at-home_opening_X',
 'bet365_1',
 'bet365_2',
 'bet365_X',
 'bet365_opening_1',
 'bet365_opening_2',
 'bet365_opening_X',
 'betclic_1',
 'betclic_2',
 'betclic_X',
 'betclic_opening_1',
 'betclic_opening_2',
 'betclic_opening_X',
 'betfair exchange_1',
 'betfair exchange_2',
 'betfair exchange_X',
 'betfair exchange_opening_1',
 'betfair exchange_opening_2',
 'betfair exchange_opening_X',
 'betfair_1',
 'betfair_2',
 'betfair_X',
 'betfair_opening_1',
 'betfair_opening_2',
 'betfair_opening_X',
 'betsafe_1',
 'betsafe_2',
 'betsafe_X',
 'betsafe_opening_1',
 'betsafe_opening_2',
 'betsafe_opening_X',
 'betsson_1',
 'betsson_2',
 'betsson_X',
 'betsson_opening_1',
 'betsson_opening_2',
 'betsson_opening_X',
 'betvictor_1',
 'betvictor_2',
 'betvictor_X',
 'betvictor_opening_1',
 'betvictor_opening_2',
 'betvictor_opening_X',
 'betway_1',
 'betway_2',
 'betway_X',
 'betway_opening_1',
 'betway_opening_2',
 'betway_opening_X',
 'bwin_1',
 'bwin_2',
 'bwin_X',
 'bwin_opening_1',
 'bwin_opening_2',
 'bwin_opening_X',
 'comeon_1',
 'comeon_2',
 'comeon_X',
 'comeon_opening_1',
 'comeon_opening_2',
 'comeon_opening_X',
 'draw_pred_transfer',
 'home_team_goal_difference',
 'home_team_goal_fatti',
 'home_team_goal_subiti',
 'home_team_points',
 'home_team_rank',
 'ht_win_pred_transfer',
 'interwetten_1',
 'interwetten_2',
 'interwetten_X',
 'interwetten_opening_1',
 'interwetten_opening_2',
 'interwetten_opening_X',
 'label',
 'league_year',
 'match_day',
 'match_hour',
 'match_month',
 'match_round',
 'match_year',
 'paddy power_1',
 'paddy power_2',
 'paddy power_X',
 'paddy power_opening_1',
 'paddy power_opening_2',
 'paddy power_opening_X',
 'pinnacle_1',
 'pinnacle_2',
 'pinnacle_X',
 'pinnacle_opening_1',
 'pinnacle_opening_2',
 'pinnacle_opening_X',
 'sbobet_1',
 'sbobet_2',
 'sbobet_X',
 'sbobet_opening_1',
 'sbobet_opening_2',
 'sbobet_opening_X',
 'unibet_1',
 'unibet_2',
 'unibet_X',
 'unibet_opening_1',
 'unibet_opening_2',
 'unibet_opening_X',
 'william hill_1',
 'william hill_2',
 'william hill_X',
 'william hill_opening_1',
 'william hill_opening_2',
 'william hill_opening_X',
 'youwin_1',
 'youwin_2',
 'youwin_X',
 'youwin_opening_1',
 'youwin_opening_2',
 'youwin_opening_X']

In [114]:
print(f"# pareggi : {list(final_df.label).count(0)} ({list(final_df.label).count(0)*100/final_df.shape[0]:.2f})")
print(f"# vittorie casa : {list(final_df.label).count(1)} ({list(final_df.label).count(1)*100/final_df.shape[0]:.2f})")
print(f"# vittorie fuori casa : {list(final_df.label).count(2)} ({list(final_df.label).count(2)*100/final_df.shape[0]:.2f})")

# pareggi : 982 (25.84)
# vittorie casa : 1737 (45.71)
# vittorie fuori casa : 1081 (28.45)

In [115]:
import lightgbm as lgb

from sklearn.model_selection import train_test_split

X = final_df.drop(['label'],axis=1)
y = final_df.label

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15,shuffle=False)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.15, shuffle=False)

In [117]:
from skopt.space import Real, Integer
from skopt.utils import use_named_args
space  = [Integer(1, 15, name='max_depth'),
          Real(10**-4, 10**0, "log-uniform", name='learning_rate'),
          Integer(50, 1000, name='n_estimators'),
          Real(0,0.01, name='reg_alpha'),
          Real(0,0.01, name='reg_lambda'),
        Integer(3,50,name='num_leaves'),
          Integer(5,30, name=' min_child_samples')
]

@use_named_args(space)
def objective(**params):
    model = lgb.LGBMClassifier(**params)
    model.fit(X_train, y_train)
    predicted_y = model.predict(X_test)
    correct = 0
    for ind,true,predicted in zip(y_test.index, y_test, predicted_y):
        if true == predicted:
            correct+=1
    return -(correct*100 / y_test.shape[0])

In [118]:
from skopt import forest_minimize
import numpy as np
res_gp = forest_minimize(objective, space, n_calls=100, random_state=42, verbose=False)

print("Best score=%.4f" % res_gp.fun)
print("""Best parameters:
- max_depth=%d
- learning_rate=%.6f
- n_estimators=%d
- reg_alpha=%d
- reg_lambda=%d
- num_leaverS=%d
-  min_child_samples=%d""" 
      % (res_gp.x[0], res_gp.x[1], 
                            res_gp.x[2], res_gp.x[3], 
                            res_gp.x[4],res_gp.x[5], res_gp.x[6]))

Best score=-57.5439
Best parameters:
- max_depth=1
- learning_rate=0.003129
- n_estimators=975
- reg_alpha=0
- reg_lambda=0
- num_leaverS=6
-  min_child_samples=14

In [119]:
model = lgb.LGBMClassifier(max_depth=1,learning_rate=0.003129, n_estimators=975, num_leaves=6,min_child_samples=14)
model.fit(X_train, y_train)
predicted_y = model.predict(X_val)
correct = 0
for ind,true,predicted in zip(y_val.index, y_val, predicted_y):
    if true == predicted:
        correct+=1
correct*100 / y_val.shape[0]

61.03092783505155

In [106]:
# baseline che usa solo le quote
result = []
for p1,pX,p2 in zip(X_val['10bet_1'], X_val['10bet_X'], X_val['10bet_2']):
    if min([p1,pX,p2]) == p1: result.append(1)
    elif min([p1,pX,p2]) == pX: result.append(0)
    else: result.append(2)

correct = 0
for ind,true,predicted in zip(y_val.index, y_val, result):
    if true == predicted:
        correct+=1
correct*100 / y_val.shape[0]

61.03092783505155

In [111]:
# baseline che usa solo le predictions
result = []
for p1,pX,p2 in zip(X_val['ht_win_pred_transfer'], X_val['draw_pred_transfer'], X_val['at_win_pred_transfer']):
    if max([p1,pX,p2]) == p1: result.append(1)
    elif max([p1,pX,p2]) == pX: result.append(0)
    else: result.append(2)

correct = 0
for ind,true,predicted in zip(y_val.index, y_val, result):
    if true == predicted:
        correct+=1
correct*100 / y_val.shape[0]

56.90721649484536

In [22]:
# mio modello
predicted_y = model.predict(X_test, raw_score =True)
predicted_y.shape

(570, 3)