In [1]:
import pandas as pd
df = pd.read_csv('../dataset/premier/lightgbm/lightgbm_base_odds_premier.csv')
df = df.sort_values(by=['match_year','match_month','match_day','match_hour','match_round','home_team','away_team']).reset_index(drop=True)
df.head()

,10bet_1,10bet_2,10bet_X,10bet_opening_1,10bet_opening_2,10bet_opening_X,188bet_1,188bet_2,188bet_X,188bet_opening_1,...,youwin_1,youwin_2,youwin_X,youwin_opening_1,youwin_opening_2,youwin_opening_X,label,match_day,match_month,match_year
0,1.12,20.70,7.96,1.15,21.60,7.63,1.18,26.00,7.50,1.22,...,1.13,17.00,6.00,1.20,13.00,5.5,1,15,8,2009
1,1.73,5.14,3.49,1.66,5.09,3.45,1.77,5.30,3.60,1.81,...,1.65,4.80,3.50,NaN,NaN,NaN,2,15,8,2009
2,3.15,2.31,3.27,3.25,2.25,3.22,3.10,2.36,3.40,3.15,...,3.00,2.20,3.25,3.25,2.10,NaN,2,15,8,2009
3,2.23,3.29,3.26,2.27,3.34,3.22,2.27,3.40,3.35,2.33,...,2.20,3.20,3.25,2.10,3.25,NaN,2,15,8,2009
4,2.87,2.61,3.12,2.96,2.57,3.08,2.90,2.60,3.30,2.95,...,2.75,2.63,3.10,2.25,3.00,3.2,2,15,8,2009

In [2]:
user_pref_df = pd.read_csv('../dataset/premier/transformed/user_prefs_premier.csv')
user_pref_df = user_pref_df.rename(columns={'match_year':'league_year'})
user_pref_df.head()

,league_year,match_round,home_team,away_team,ht_win_pred_transfer,draw_pred_transfer,at_win_pred_transfer
0,2009,1,Chelsea,Hull City,100.0,0.0,0.0
1,2009,1,Aston Villa,Wigan,88.1,9.5,2.4
2,2009,1,Wolves,West Ham,11.9,31.0,57.1
3,2009,1,Stoke City,Burnley,54.8,35.7,9.5
4,2009,1,Portsmouth,Fulham,33.3,35.7,31.0

In [3]:
sorted(set(df.away_team))

['Arsenal',
 'Aston Villa',
 'Birmingham',
 'Blackburn',
 'Blackpool',
 'Bolton',
 'Bournemouth',
 'Brighton',
 'Burnley',
 'Cardiff',
 'Chelsea',
 'Crystal Palace',
 'Everton',
 'Fulham',
 'Huddersfield',
 'Hull',
 'Leicester',
 'Liverpool',
 'Manchester City',
 'Manchester Utd',
 'Middlesbrough',
 'Newcastle',
 'Norwich',
 'Portsmouth',
 'QPR',
 'Reading',
 'Southampton',
 'Stoke',
 'Sunderland',
 'Swansea',
 'Tottenham',
 'Watford',
 'West Brom',
 'West Ham',
 'Wigan',
 'Wolves']

In [4]:
sorted(set(user_pref_df.away_team))

['Arsenal',
 'Aston Villa',
 'Birmingham',
 'Blackburn',
 'Blackpool',
 'Bolton',
 'Bournemouth',
 'Brighton',
 'Burnley',
 'Cardiff',
 'Chelsea',
 'Crystal Palace',
 'Everton',
 'Fulham',
 'Huddersfield',
 'Hull City',
 'Leicester',
 'Liverpool',
 'Man City',
 'Man Utd',
 'Middlesbrough',
 'Newcastle',
 'Norwich',
 'Portsmouth',
 'QPR',
 'Reading',
 'Southampton',
 'Spurs',
 'Stoke City',
 'Sunderland',
 'Swansea',
 'Watford',
 'West Brom',
 'West Ham',
 'Wigan',
 'Wolves']

In [5]:
user_pref_df.loc[user_pref_df.home_team == 'Spurs', 'home_team'] = 'Tottenham'
user_pref_df.loc[user_pref_df.away_team == 'Spurs', 'away_team'] = 'Tottenham'
user_pref_df.loc[user_pref_df.home_team == 'Hull City', 'home_team'] = 'Hull'
user_pref_df.loc[user_pref_df.away_team == 'Hull City', 'away_team'] = 'Hull'
user_pref_df.loc[user_pref_df.home_team == 'Man Utd', 'home_team'] = 'Manchester Utd'
user_pref_df.loc[user_pref_df.away_team == 'Man Utd', 'away_team'] = 'Manchester Utd'
user_pref_df.loc[user_pref_df.home_team == 'Man City', 'home_team'] = 'Manchester City'
user_pref_df.loc[user_pref_df.away_team == 'Man City', 'away_team'] = 'Manchester City'
user_pref_df.loc[user_pref_df.home_team == 'Stoke City', 'home_team'] = 'Stoke'
user_pref_df.loc[user_pref_df.away_team == 'Stoke City', 'away_team'] = 'Stoke'

In [6]:
sorted(set(user_pref_df.away_team)) == sorted(set(df.away_team)) and sorted(set(user_pref_df.home_team)) == sorted(set(df.home_team))

True

In [7]:
user_pref_df.sort_values(by=['league_year','match_round','home_team','away_team']).head(19)

,league_year,match_round,home_team,away_team,ht_win_pred_transfer,draw_pred_transfer,at_win_pred_transfer
1,2009,1,Aston Villa,Wigan,88.1,9.5,2.4
6,2009,1,Blackburn,Manchester City,7.1,16.7,76.2
5,2009,1,Bolton,Sunderland,45.2,45.2,9.5
0,2009,1,Chelsea,Hull,100.0,0.0,0.0
7,2009,1,Everton,Arsenal,16.7,28.6,54.8
8,2009,1,Manchester Utd,Birmingham,100.0,0.0,0.0
4,2009,1,Portsmouth,Fulham,33.3,35.7,31.0
3,2009,1,Stoke,Burnley,54.8,35.7,9.5
9,2009,1,Tottenham,Liverpool,4.8,31.0,64.3
2,2009,1,Wolves,West Ham,11.9,31.0,57.1
18,2009,2,Arsenal,Bolton,-1.0,-1.0,-1.0
13,2009,2,Birmingham,Portsmouth,30.4,56.5,13.0
12,2009,2,Burnley,Manchester Utd,0.0,0.0,100.0
17,2009,2,Fulham,Blackburn,71.0,16.1,12.9
15,2009,2,Hull,Tottenham,21.7,26.1,52.2
14,2009,2,Liverpool,Stoke,100.0,0.0,0.0
19,2009,2,Manchester City,Everton,84.6,10.3,5.1
11,2009,2,Sunderland,Chelsea,0.0,4.8,95.2
16,2009,2,West Ham,Aston Villa,42.9,28.6,28.6

In [8]:
class_df = pd.read_csv('../dataset/premier/transformed/classifica_premier_0919.csv')
class_df = class_df.rename(columns={'match_year':'league_year'})
class_df.head()

,league_year,match_round,team,team_rank,team_points,team_goal_difference,team_goal_fatti,team_goal_subiti
0,2009,2,Arsenal,1,3,5,6,1
1,2009,2,West Ham,2,3,2,2,0
2,2009,2,Man City,3,3,2,2,0
3,2009,2,Wigan,4,3,2,2,0
4,2009,2,Stoke City,5,3,2,2,0

In [9]:
[x for x in list(set(class_df.team)) if x not in list(set(user_pref_df.away_team))]

['Hull City', 'Spurs', 'Man Utd', 'Stoke City', 'Man City']

In [10]:
class_df.loc[class_df.team == 'Spurs', 'team'] = 'Tottenham'
class_df.loc[class_df.team == 'Hull City', 'team'] = 'Hull'
class_df.loc[class_df.team == 'Man Utd', 'team'] = 'Manchester Utd'
class_df.loc[class_df.team == 'Man City', 'team'] = 'Manchester City'
class_df.loc[class_df.team == 'Stoke City', 'team'] = 'Stoke'

In [11]:
sorted(list(set(class_df.team))) == sorted(set(user_pref_df.away_team)) == sorted(set(df.away_team))

True

In [12]:
tmp = pd.merge(user_pref_df, class_df.add_prefix('home_'), how='left', left_on=['league_year','match_round','home_team'], right_on=['home_league_year','home_match_round','home_team']).fillna(0).drop(['home_league_year','home_match_round'],axis=1)
tmp = pd.merge(tmp, class_df.add_prefix('away_'), how='left', left_on=['league_year','match_round','away_team'], right_on=['away_league_year','away_match_round','away_team']).fillna(0).drop(['away_league_year','away_match_round'],axis=1)
tmp[tmp.columns[7:]] = tmp[tmp.columns[7:]].astype(int)
tmp.head()

,league_year,match_round,home_team,away_team,ht_win_pred_transfer,draw_pred_transfer,at_win_pred_transfer,home_team_rank,home_team_points,home_team_goal_difference,home_team_goal_fatti,home_team_goal_subiti,away_team_rank,away_team_points,away_team_goal_difference,away_team_goal_fatti,away_team_goal_subiti
0,2009,1,Chelsea,Hull,100.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0
1,2009,1,Aston Villa,Wigan,88.1,9.5,2.4,0,0,0,0,0,0,0,0,0,0
2,2009,1,Wolves,West Ham,11.9,31.0,57.1,0,0,0,0,0,0,0,0,0,0
3,2009,1,Stoke,Burnley,54.8,35.7,9.5,0,0,0,0,0,0,0,0,0,0
4,2009,1,Portsmouth,Fulham,33.3,35.7,31.0,0,0,0,0,0,0,0,0,0,0

In [13]:
tmp_df = pd.merge(df, tmp, how='left',on=['league_year', 'match_round','home_team','away_team'])
tmp_df.head()

,10bet_1,10bet_2,10bet_X,10bet_opening_1,10bet_opening_2,10bet_opening_X,188bet_1,188bet_2,188bet_X,188bet_opening_1,...,home_team_rank,home_team_points,home_team_goal_difference,home_team_goal_fatti,home_team_goal_subiti,away_team_rank,away_team_points,away_team_goal_difference,away_team_goal_fatti,away_team_goal_subiti
0,1.12,20.70,7.96,1.15,21.60,7.63,1.18,26.00,7.50,1.22,...,0,0,0,0,0,0,0,0,0,0
1,1.73,5.14,3.49,1.66,5.09,3.45,1.77,5.30,3.60,1.81,...,0,0,0,0,0,0,0,0,0,0
2,3.15,2.31,3.27,3.25,2.25,3.22,3.10,2.36,3.40,3.15,...,0,0,0,0,0,0,0,0,0,0
3,2.23,3.29,3.26,2.27,3.34,3.22,2.27,3.40,3.35,2.33,...,0,0,0,0,0,0,0,0,0,0
4,2.87,2.61,3.12,2.96,2.57,3.08,2.90,2.60,3.30,2.95,...,0,0,0,0,0,0,0,0,0,0

In [14]:
sorted(tmp_df.columns)

['10bet_1',
 '10bet_2',
 '10bet_X',
 '10bet_opening_1',
 '10bet_opening_2',
 '10bet_opening_X',
 '188bet_1',
 '188bet_2',
 '188bet_X',
 '188bet_opening_1',
 '188bet_opening_2',
 '188bet_opening_X',
 '1xbet_1',
 '1xbet_2',
 '1xbet_X',
 '1xbet_opening_1',
 '1xbet_opening_2',
 '1xbet_opening_X',
 '888sport_1',
 '888sport_2',
 '888sport_X',
 '888sport_opening_1',
 '888sport_opening_2',
 '888sport_opening_X',
 'at_win_pred_transfer',
 'away_goals',
 'away_team',
 'away_team_goal_difference',
 'away_team_goal_fatti',
 'away_team_goal_subiti',
 'away_team_points',
 'away_team_rank',
 'bet-at-home_1',
 'bet-at-home_2',
 'bet-at-home_X',
 'bet-at-home_opening_1',
 'bet-at-home_opening_2',
 'bet-at-home_opening_X',
 'bet365_1',
 'bet365_2',
 'bet365_X',
 'bet365_opening_1',
 'bet365_opening_2',
 'bet365_opening_X',
 'betclic_1',
 'betclic_2',
 'betclic_X',
 'betclic_opening_1',
 'betclic_opening_2',
 'betclic_opening_X',
 'betfair exchange_1',
 'betfair exchange_2',
 'betfair exchange_X',
 'betfair exchange_opening_1',
 'betfair exchange_opening_2',
 'betfair exchange_opening_X',
 'betfair_1',
 'betfair_2',
 'betfair_X',
 'betfair_opening_1',
 'betfair_opening_2',
 'betfair_opening_X',
 'betsafe_1',
 'betsafe_2',
 'betsafe_X',
 'betsafe_opening_1',
 'betsafe_opening_2',
 'betsafe_opening_X',
 'betsson_1',
 'betsson_2',
 'betsson_X',
 'betsson_opening_1',
 'betsson_opening_2',
 'betsson_opening_X',
 'betvictor_1',
 'betvictor_2',
 'betvictor_X',
 'betvictor_opening_1',
 'betvictor_opening_2',
 'betvictor_opening_X',
 'betway_1',
 'betway_2',
 'betway_X',
 'betway_opening_1',
 'betway_opening_2',
 'betway_opening_X',
 'bwin_1',
 'bwin_2',
 'bwin_X',
 'bwin_opening_1',
 'bwin_opening_2',
 'bwin_opening_X',
 'comeon_1',
 'comeon_2',
 'comeon_X',
 'comeon_opening_1',
 'comeon_opening_2',
 'comeon_opening_X',
 'draw_pred_transfer',
 'home_goals',
 'home_team',
 'home_team_goal_difference',
 'home_team_goal_fatti',
 'home_team_goal_subiti',
 'home_team_points',
 'home_team_rank',
 'ht_win_pred_transfer',
 'interwetten_1',
 'interwetten_2',
 'interwetten_X',
 'interwetten_opening_1',
 'interwetten_opening_2',
 'interwetten_opening_X',
 'label',
 'league_year',
 'match_date',
 'match_day',
 'match_hour',
 'match_month',
 'match_round',
 'match_year',
 'paddy power_1',
 'paddy power_2',
 'paddy power_X',
 'paddy power_opening_1',
 'paddy power_opening_2',
 'paddy power_opening_X',
 'pinnacle_1',
 'pinnacle_2',
 'pinnacle_X',
 'pinnacle_opening_1',
 'pinnacle_opening_2',
 'pinnacle_opening_X',
 'sbobet_1',
 'sbobet_2',
 'sbobet_X',
 'sbobet_opening_1',
 'sbobet_opening_2',
 'sbobet_opening_X',
 'unibet_1',
 'unibet_2',
 'unibet_X',
 'unibet_opening_1',
 'unibet_opening_2',
 'unibet_opening_X',
 'william hill_1',
 'william hill_2',
 'william hill_X',
 'william hill_opening_1',
 'william hill_opening_2',
 'william hill_opening_X',
 'youwin_1',
 'youwin_2',
 'youwin_X',
 'youwin_opening_1',
 'youwin_opening_2',
 'youwin_opening_X']

In [15]:
final_df = tmp_df.drop(['match_date','home_team','away_team','home_goals','away_goals'], axis=1)
final_df = final_df.sort_values(by = ['league_year', 'match_round']).reset_index(drop=True)
final_df = final_df.fillna(0)
final_df.head()

,10bet_1,10bet_2,10bet_X,10bet_opening_1,10bet_opening_2,10bet_opening_X,188bet_1,188bet_2,188bet_X,188bet_opening_1,...,home_team_rank,home_team_points,home_team_goal_difference,home_team_goal_fatti,home_team_goal_subiti,away_team_rank,away_team_points,away_team_goal_difference,away_team_goal_fatti,away_team_goal_subiti
0,1.12,20.70,7.96,1.15,21.60,7.63,1.18,26.00,7.50,1.22,...,0,0,0,0,0,0,0,0,0,0
1,1.73,5.14,3.49,1.66,5.09,3.45,1.77,5.30,3.60,1.81,...,0,0,0,0,0,0,0,0,0,0
2,3.15,2.31,3.27,3.25,2.25,3.22,3.10,2.36,3.40,3.15,...,0,0,0,0,0,0,0,0,0,0
3,2.23,3.29,3.26,2.27,3.34,3.22,2.27,3.40,3.35,2.33,...,0,0,0,0,0,0,0,0,0,0
4,2.87,2.61,3.12,2.96,2.57,3.08,2.90,2.60,3.30,2.95,...,0,0,0,0,0,0,0,0,0,0

In [16]:
sorted(final_df.columns)

['10bet_1',
 '10bet_2',
 '10bet_X',
 '10bet_opening_1',
 '10bet_opening_2',
 '10bet_opening_X',
 '188bet_1',
 '188bet_2',
 '188bet_X',
 '188bet_opening_1',
 '188bet_opening_2',
 '188bet_opening_X',
 '1xbet_1',
 '1xbet_2',
 '1xbet_X',
 '1xbet_opening_1',
 '1xbet_opening_2',
 '1xbet_opening_X',
 '888sport_1',
 '888sport_2',
 '888sport_X',
 '888sport_opening_1',
 '888sport_opening_2',
 '888sport_opening_X',
 'at_win_pred_transfer',
 'away_team_goal_difference',
 'away_team_goal_fatti',
 'away_team_goal_subiti',
 'away_team_points',
 'away_team_rank',
 'bet-at-home_1',
 'bet-at-home_2',
 'bet-at-home_X',
 'bet-at-home_opening_1',
 'bet-at-home_opening_2',
 'bet-at-home_opening_X',
 'bet365_1',
 'bet365_2',
 'bet365_X',
 'bet365_opening_1',
 'bet365_opening_2',
 'bet365_opening_X',
 'betclic_1',
 'betclic_2',
 'betclic_X',
 'betclic_opening_1',
 'betclic_opening_2',
 'betclic_opening_X',
 'betfair exchange_1',
 'betfair exchange_2',
 'betfair exchange_X',
 'betfair exchange_opening_1',
 'betfair exchange_opening_2',
 'betfair exchange_opening_X',
 'betfair_1',
 'betfair_2',
 'betfair_X',
 'betfair_opening_1',
 'betfair_opening_2',
 'betfair_opening_X',
 'betsafe_1',
 'betsafe_2',
 'betsafe_X',
 'betsafe_opening_1',
 'betsafe_opening_2',
 'betsafe_opening_X',
 'betsson_1',
 'betsson_2',
 'betsson_X',
 'betsson_opening_1',
 'betsson_opening_2',
 'betsson_opening_X',
 'betvictor_1',
 'betvictor_2',
 'betvictor_X',
 'betvictor_opening_1',
 'betvictor_opening_2',
 'betvictor_opening_X',
 'betway_1',
 'betway_2',
 'betway_X',
 'betway_opening_1',
 'betway_opening_2',
 'betway_opening_X',
 'bwin_1',
 'bwin_2',
 'bwin_X',
 'bwin_opening_1',
 'bwin_opening_2',
 'bwin_opening_X',
 'comeon_1',
 'comeon_2',
 'comeon_X',
 'comeon_opening_1',
 'comeon_opening_2',
 'comeon_opening_X',
 'draw_pred_transfer',
 'home_team_goal_difference',
 'home_team_goal_fatti',
 'home_team_goal_subiti',
 'home_team_points',
 'home_team_rank',
 'ht_win_pred_transfer',
 'interwetten_1',
 'interwetten_2',
 'interwetten_X',
 'interwetten_opening_1',
 'interwetten_opening_2',
 'interwetten_opening_X',
 'label',
 'league_year',
 'match_day',
 'match_hour',
 'match_month',
 'match_round',
 'match_year',
 'paddy power_1',
 'paddy power_2',
 'paddy power_X',
 'paddy power_opening_1',
 'paddy power_opening_2',
 'paddy power_opening_X',
 'pinnacle_1',
 'pinnacle_2',
 'pinnacle_X',
 'pinnacle_opening_1',
 'pinnacle_opening_2',
 'pinnacle_opening_X',
 'sbobet_1',
 'sbobet_2',
 'sbobet_X',
 'sbobet_opening_1',
 'sbobet_opening_2',
 'sbobet_opening_X',
 'unibet_1',
 'unibet_2',
 'unibet_X',
 'unibet_opening_1',
 'unibet_opening_2',
 'unibet_opening_X',
 'william hill_1',
 'william hill_2',
 'william hill_X',
 'william hill_opening_1',
 'william hill_opening_2',
 'william hill_opening_X',
 'youwin_1',
 'youwin_2',
 'youwin_X',
 'youwin_opening_1',
 'youwin_opening_2',
 'youwin_opening_X']

In [17]:
print(f"# pareggi : {list(final_df.label).count(0)} ({list(final_df.label).count(0)*100/final_df.shape[0]:.2f})")
print(f"# vittorie casa : {list(final_df.label).count(1)} ({list(final_df.label).count(1)*100/final_df.shape[0]:.2f})")
print(f"# vittorie fuori casa : {list(final_df.label).count(2)} ({list(final_df.label).count(2)*100/final_df.shape[0]:.2f})")

# pareggi : 940 (24.74)
# vittorie casa : 1758 (46.26)
# vittorie fuori casa : 1102 (29.00)

In [45]:
import lightgbm as lgb

from sklearn.model_selection import train_test_split

X = final_df.drop(['label'],axis=1)
y = final_df.label

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15,shuffle=False)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.15, shuffle=False)

In [19]:
from skopt.space import Real, Integer
from skopt.utils import use_named_args
space  = [Integer(1, 20, name='max_depth'),
          Real(10**-4, 10**0, "log-uniform", name='learning_rate'),
          Integer(50, 1500, name='n_estimators'),
        Integer(3,50,name='num_leaves'),
          Integer(5,30, name=' min_child_samples')
]

@use_named_args(space)
def objective(**params):
    model = lgb.LGBMClassifier(**params)
    model.fit(X_train, y_train)
    predicted_y = model.predict(X_test)
    correct = 0
    for ind,true,predicted in zip(y_test.index, y_test, predicted_y):
        if true == predicted:
            correct+=1
    return -(correct*100 / y_test.shape[0])

C:\Users\BlueAce17\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)

In [20]:
from skopt import forest_minimize
import numpy as np
res_gp = forest_minimize(objective, space, n_calls=10, random_state=42, verbose=False)

print("Best score=%.4f" % res_gp.fun)
print("""Best parameters:
- max_depth=%d
- learning_rate=%.6f
- n_estimators=%d
- num_leaver=%d
-  min_child_samples=%d""" 
      % (res_gp.x[0], res_gp.x[1], 
                            res_gp.x[2], res_gp.x[3], 
                            res_gp.x[4]))

Best score=-53.8596
Best parameters:
- max_depth=15
- learning_rate=0.006672
- n_estimators=736
- num_leaver=46
-  min_child_samples=27

In [21]:
model = lgb.LGBMClassifier(max_depth=4,learning_rate=0.001287, n_estimators=868, num_leaves=34,min_child_samples=29)
model.fit(X_train, y_train)
predicted_y = model.predict(X_val)
correct = 0
for ind,true,predicted in zip(y_val.index, y_val, predicted_y):
    if true == predicted:
        correct+=1
correct*100 / y_val.shape[0]

60.20618556701031

In [22]:
# baseline che usa solo le quote
result = []
for p1,pX,p2 in zip(X_val['10bet_1'], X_val['10bet_X'], X_val['10bet_2']):
    if min([p1,pX,p2]) == p1: result.append(1)
    elif min([p1,pX,p2]) == pX: result.append(0)
    else: result.append(2)

correct = 0
for ind,true,predicted in zip(y_val.index, y_val, result):
    if true == predicted:
        correct+=1
correct*100 / y_val.shape[0]

60.0

In [23]:
# baseline che usa solo le predictions
result = []
for p1,pX,p2 in zip(X_val['ht_win_pred_transfer'], X_val['draw_pred_transfer'], X_val['at_win_pred_transfer']):
    if max([p1,pX,p2]) == p1: result.append(1)
    elif max([p1,pX,p2]) == pX: result.append(0)
    else: result.append(2)

correct = 0
for ind,true,predicted in zip(y_val.index, y_val, result):
    if true == predicted:
        correct+=1
correct*100 / y_val.shape[0]

56.70103092783505

In [24]:
# mio modello
predicted_y = model.predict(X_test, raw_score =True)
predicted_y.shape

(570, 3)

In [25]:
final_df[final_df.league_year==2018]

,10bet_1,10bet_2,10bet_X,10bet_opening_1,10bet_opening_2,10bet_opening_X,188bet_1,188bet_2,188bet_X,188bet_opening_1,...,home_team_rank,home_team_points,home_team_goal_difference,home_team_goal_fatti,home_team_goal_subiti,away_team_rank,away_team_points,away_team_goal_difference,away_team_goal_fatti,away_team_goal_subiti
3420,1.56,7.00,3.80,1.40,8.50,4.45,1.55,6.80,4.00,1.32,...,0,0,0,0,0,0,0,0,0,0
3421,4.75,1.87,3.40,4.40,1.83,3.60,4.40,1.88,3.55,4.05,...,0,0,0,0,0,0,0,0,0,0
3422,1.87,4.35,3.65,1.83,4.65,3.50,1.86,4.35,3.65,2.03,...,0,0,0,0,0,0,0,0,0,0
3423,2.55,2.80,3.40,2.30,3.20,3.30,2.56,2.82,3.35,2.36,...,0,0,0,0,0,0,0,0,0,0
3424,6.70,1.57,3.85,6.15,1.54,4.10,6.60,1.57,3.90,6.00,...,0,0,0,0,0,0,0,0,0,0
3425,2.50,3.15,3.05,2.25,3.30,3.25,2.51,3.05,3.15,2.25,...,0,0,0,0,0,0,0,0,0,0
3426,2.40,3.25,3.15,2.50,2.90,3.30,2.38,3.20,3.25,2.50,...,0,0,0,0,0,0,0,0,0,0
3427,1.24,12.00,6.80,1.33,9.75,5.00,1.22,12.50,6.90,1.28,...,0,0,0,0,0,0,0,0,0,0
3428,2.00,4.40,3.20,1.95,4.10,3.45,2.05,4.20,3.20,1.98,...,0,0,0,0,0,0,0,0,0,0
3429,4.25,1.80,3.95,3.85,1.91,3.80,4.25,1.81,3.95,3.30,...,0,0,0,0,0,0,0,0,0,0
3430,3.20,2.40,3.15,2.50,2.90,3.10,3.30,2.40,3.10,2.53,...,17,0,-2,0,2,14,0,-1,1,2
3431,1.83,4.75,3.55,2.30,3.15,3.20,1.83,4.65,3.55,2.31,...,9,1,0,2,2,12,1,0,0,0
3432,2.15,3.60,3.35,1.83,4.40,3.45,2.19,3.50,3.40,1.85,...,13,0,-1,1,2,10,1,0,2,2
3433,1.24,12.25,6.35,1.19,14.50,6.50,1.26,11.50,6.20,1.19,...,8,3,1,2,1,18,0,-2,0,2
3434,2.05,3.60,3.50,2.15,3.50,3.20,2.07,3.60,3.55,2.19,...,20,0,-4,0,4,5,3,2,2,0
3435,1.83,4.40,3.75,1.83,4.45,3.50,1.85,4.40,3.70,1.83,...,2,3,3,3,0,15,0,-2,0,2
3436,2.40,3.30,3.05,2.35,3.15,3.05,2.44,3.30,3.05,2.31,...,11,1,0,0,0,6,3,2,2,0
3437,1.07,30.75,13.50,1.10,20.00,9.25,1.08,31.00,12.00,1.11,...,3,3,2,2,0,19,0,-3,0,3
3438,5.85,1.69,3.55,5.25,1.71,3.45,5.50,1.71,3.65,4.30,...,16,0,-2,0,2,7,3,1,2,1
3439,7.75,1.39,5.20,5.70,1.56,4.10,8.00,1.39,5.00,4.65,...,4,3,2,2,0,1,3,4,4,0
3440,12.25,1.28,5.70,9.50,1.27,5.70,10.50,1.31,5.40,8.90,...,14,1,-2,2,4,1,6,7,8,1
3441,1.34,8.50,5.55,1.39,7.75,4.50,1.35,8.30,5.50,1.48,...,17,0,-3,2,5,19,0,-5,1,6
3442,2.60,2.70,3.45,2.30,3.05,3.30,2.63,2.68,3.45,2.29,...,6,6,3,4,1,7,4,1,4,3
3443,2.40,3.45,3.00,2.10,3.70,3.15,2.38,3.45,3.00,2.16,...,20,0,-8,1,9,16,1,-2,0,2
3444,2.30,3.35,3.20,2.25,3.25,3.25,2.31,3.35,3.20,2.09,...,13,1,-1,1,2,8,3,1,3,2
3445,1.12,21.75,9.25,1.19,15.50,6.45,1.13,21.00,9.50,1.19,...,2,6,6,6,0,11,3,-1,3,4
3446,2.35,3.20,3.30,2.35,3.15,3.15,2.28,3.25,3.35,2.40,...,4,6,4,5,1,10,3,0,2,2
3447,2.20,3.65,3.20,2.40,3.05,3.15,2.20,3.55,3.30,2.44,...,18,0,-4,1,5,15,1,-2,1,3
3448,6.40,1.54,4.15,4.45,1.83,3.50,6.20,1.55,4.20,4.10,...,12,1,-1,1,2,3,6,4,6,2
3449,2.55,2.90,3.25,2.10,3.60,3.25,2.56,2.85,3.30,2.04,...,9,3,0,4,4,5,6,3,5,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3770,1.05,26.00,11.75,1.06,18.50,9.75,1.07,31.00,13.00,1.06,...,2,88,59,79,20,20,14,-49,20,69
3771,1.33,8.00,5.15,1.42,5.90,4.45,1.35,8.70,5.30,1.35,...,3,70,30,65,35,11,43,-10,44,54
3772,2.90,2.40,3.20,2.25,2.95,3.15,3.00,2.49,3.25,2.31,...,12,42,-5,43,48,9,49,6,50,44
3773,2.15,3.15,3.40,2.30,2.80,3.20,2.21,3.25,3.55,2.33,...,19,23,-43,33,76,18,31,-35,30,65
3774,1.74,4.25,3.75,1.77,4.25,3.40,1.80,4.25,3.95,1.89,...,16,37,-17,41,58,14,41,-13,49,62
3775,2.55,2.80,3.05,2.55,2.55,3.15,2.69,2.80,3.20,2.53,...,8,50,0,50,50,7,51,1,44,43
3776,2.10,3.55,3.15,2.15,3.30,3.05,2.19,3.65,3.25,2.33,...,17,34,-22,32,54,13,41,-9,35,44
3777,2.50,2.55,3.45,2.65,2.30,3.45,2.61,2.61,3.60,2.55,...,10,48,1,48,47,5,66,23,69,46
3778,14.50,1.13,8.00,13.50,1.14,6.65,16.50,1.17,7.80,13.00,...,15,40,-18,44,62,1,89,67,89,22
3779,2.60,2.60,3.20,2.20,2.80,3.45,2.69,2.69,3.35,2.31,...,6,64,13,63,50,4,67,21,59,38
3780,1.65,5.20,3.65,1.57,5.10,3.70,1.68,5.30,3.85,1.62,...,9,50,6,50,44,15,40,-19,44,63
3781,5.40,1.51,4.40,4.10,1.69,3.80,5.70,1.55,4.50,3.95,...,14,42,-13,52,65,3,70,29,65,36
3782,2.25,2.95,3.40,2.10,3.05,3.35,2.36,3.00,3.55,2.26,...,11,46,-9,45,54,16,38,-17,44,61
3783,1.44,7.00,4.10,1.45,6.10,4.00,1.48,7.50,4.35,1.56,...,7,54,2,46,44,19,26,-42,34,76
3784,2.45,2.60,3.55,2.75,2.50,3.00,2.53,2.65,3.70,2.80,...,18,31,-36,30,66,12,43,-5,43,48
3785,8.25,1.31,5.20,9.00,1.25,5.30,8.70,1.35,5.30,9.00,...,13,42,-9,36,45,2,91,64,84,20
3786,1.28,9.00,5.55,1.32,7.50,4.80,1.31,9.30,5.80,1.45,...,4,68,21,60,39,10,50,-1,51,52
3787,8.50,1.30,5.25,7.75,1.33,4.60,9.20,1.34,5.30,7.70,...,20,14,-54,20,74,6,65,13,64,51
3788,1.25,10.50,5.70,1.27,9.00,5.00,1.27,11.50,5.90,1.36,...,5,66,20,69,49,17,35,-22,33,55
3789,1.14,13.00,8.00,1.09,17.50,8.25,1.17,16.00,7.90,1.09,...,1,92,68,90,22,8,51,4,51,47
3790,12.25,1.18,6.90,18.25,1.06,9.75,15.50,1.19,7.20,16.00,...,17,36,-22,34,56,1,95,69,91,22
3791,2.45,2.65,3.45,4.00,1.74,3.65,2.50,2.75,3.65,3.85,...,15,40,-21,44,65,5,67,20,70,50
3792,1.74,4.05,4.00,1.95,3.45,3.35,1.74,4.30,4.25,2.00,...,12,46,-4,46,50,13,45,-12,53,65
3793,2.35,2.80,3.35,2.75,2.35,3.20,2.40,2.90,3.60,2.73,...,19,26,-43,34,77,14,42,-10,38,48
3794,2.30,2.85,3.45,3.75,1.91,3.30,2.36,2.95,3.65,3.55,...,9,51,3,51,48,3,71,24,63,39
3795,1.29,8.50,5.50,1.09,18.25,8.00,1.31,9.70,5.70,1.13,...,2,94,65,87,22,7,57,3,47,44
3796,1.27,8.50,5.75,1.10,15.50,8.00,1.32,8.30,6.00,1.12,...,6,66,13,65,52,18,31,-37,32,69
3797,1.36,7.25,4.80,1.37,7.00,4.25,1.36,8.40,5.30,1.39,...,16,38,-20,44,64,20,15,-54,21,75
3798,1.87,3.85,3.60,1.48,5.85,3.95,1.92,3.95,3.75,1.60,...,4,70,28,65,37,8,53,8,52,44
3799,2.05,3.25,3.60,1.71,4.25,3.55,2.07,3.30,3.85,1.83,...,10,50,-4,51,55,11,49,-6,48,54

# Proviamo Logistic Regression

In [28]:
dataset_2018 = final_df[final_df.league_year==2018].reset_index(drop=True)

In [29]:
dataset_2018.head()

,10bet_1,10bet_2,10bet_X,10bet_opening_1,10bet_opening_2,10bet_opening_X,188bet_1,188bet_2,188bet_X,188bet_opening_1,...,home_team_rank,home_team_points,home_team_goal_difference,home_team_goal_fatti,home_team_goal_subiti,away_team_rank,away_team_points,away_team_goal_difference,away_team_goal_fatti,away_team_goal_subiti
0,1.56,7.00,3.80,1.40,8.50,4.45,1.55,6.80,4.00,1.32,...,0,0,0,0,0,0,0,0,0,0
1,4.75,1.87,3.40,4.40,1.83,3.60,4.40,1.88,3.55,4.05,...,0,0,0,0,0,0,0,0,0,0
2,1.87,4.35,3.65,1.83,4.65,3.50,1.86,4.35,3.65,2.03,...,0,0,0,0,0,0,0,0,0,0
3,2.55,2.80,3.40,2.30,3.20,3.30,2.56,2.82,3.35,2.36,...,0,0,0,0,0,0,0,0,0,0
4,6.70,1.57,3.85,6.15,1.54,4.10,6.60,1.57,3.90,6.00,...,0,0,0,0,0,0,0,0,0,0

In [50]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logreg = LogisticRegression(penalty='l2', max_iter=200)
logreg.fit(X_train, y_train)

C:\Users\BlueAce17\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\BlueAce17\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=200,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [51]:
y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.52